# JPA
spring:
  config:
    import:
      - classpath:/application-secret.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.1.3:3306/fitow
#    url: jdbc:mysql://192.168.0.101:3306/fitow
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          timeout: 50000 # SMTP 서버에 연결을 시도하고 응답을 기다리는 최대 시간이 50,000ms
          starttls.enable: true
          ssl.trust: smtp.gmail.com
  data:
    redis:
      host: 172.30.1.3
#      host: 192.168.0.101
      port: 6379
  mvc:
    hiddenmethod:
      filter:
        enabled: true #form태그에는 PUT, DELETE를 지원하지 않아 GET으로 처리됨. 타임리프 th:method 사용하여 처리
  thymeleaf:
    prefix: file:src/main/resources/templates/
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  profile_img_dir: C:\Users\ericn\Desktop\fitow\images\profile\